### ISSUE TITLE
Implement All Options Strategies

### ISSUE THREAD

**Issue by joaquinbejar** [joaquinbejar/OptionStratLib#15]
## Description
This is a tracking issue to implement the core logic for all options trading strategies. Each strategy will be implemented in its own issue, with subtasks for the required traits.

### Strategies to Implement:
- [ ] **Bear Put Spread** (#16)
- [ ] **Bull Call Spread** (#17)
- [ ] **Butterfly Spread** (#18)
- [ ] **Call Butterfly** (#19)
- [ ] **Collar** (#20)
- [ ] **Covered Call** (#21)
- [ ] **Custom** (#22)
- [ ] **Iron Condor** (#23)
- [ ] **Poor Man's Covered Call** (#24)
- [ ] **Protective Put** (#25)
- [ ] **Straddle** (#26)
- [ ] **Strangle** (#27)

Each strategy will have its own issue detailing specific implementation tasks.

---

## Labels
`tracking`, `strategies`

---
